version: "3"

services:
  game-keys-store-server:
    container_name: game-keys-store-server
    build: .
    ports:
      - 8080:8080
  mysql-db:
    container_name: mysql-db
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=game_keys_db_mysql
  redis:
    container_name: redis
    image: redis:6.0.6
    ports:
      - 6379:6379
    restart: always