version: "3"

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=game_keys_db_mysql