#dbConnection : "root:root@tcp(mysql-db:3306)/game_keys_db_mysql"
dbConnection : "jhjze9mu560gqoaj:njwi545nf282cb92@tcp(qn0cquuabmqczee2.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306)/iuauiu9e6bbl4cfd"
port : ":8080"
#redisConnection : "redis:6379"
redisConnection : "ec2-54-235-169-237.compute-1.amazonaws.com:11559"
redisPassword : "p9d46e1338b8869085f9e9a904b27cd4809fb8dac57b0014ed0a8c584684af589"
#redisPassword : ""
accessSecret : "asdfkasdflkadjsfskl"
refreshSecret : "sdlfkjio3rwefjnlksdfjo"
platformFeeShare : 0.05
platformAccount : "2398471212390412384"
platformEmail : "tyrlybeam@gmail.com"
platformEmailPassword : "73918183"
notificationSalt : "salt"